Ajustes Workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,13 +27,19 @@ jobs:
         cache: 'npm'
 
     - name: Install dependencies
-      run: npm ci
+      run: npm install
 
-    - name: Run lint
-      run: npm run lint
-
-    - name: Build application
+    - name: Build project
       run: npm run build
+
+    - name: Check build artifacts
+      run: |
+        if [ -d "dist" ]; then
+          echo "Build successful: 'dist' directory exists."
+        else
+          echo "Build failed: 'dist' directory missing."
+          exit 1
+        fi
 
     - name: Log in to Docker Hub
       uses: docker/login-action@v3
